# name: Fabric Project Tests

# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main, develop ]

# jobs:
#   test-chaincode:
#     name: Test Go Chaincode
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.20'
      
#       - name: Install dependencies
#         run: |
#           cd chaincode-go
#           go get ./...
      
#       - name: Run Go Tests
#         run: |
#           cd chaincode-go
#           go test -v ./chaincode/...
      
#       - name: Verify Build
#         run: |
#           cd chaincode-go
#           go build -v .

#   test-api:
#     name: Test TypeScript API
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
      
#       - name: Install dependencies
#         run: |
#           cd application
#           npm ci
      
#       - name: Build
#         run: |
#           cd application
#           npm run build
      
#       - name: Run unit tests
#         run: |
#           cd application
#           npm test -- --testMatch '**/*.test.ts' --testPathIgnorePatterns 'integration'
      
#       # Integration tests would require a running Fabric network
#       # and are better run in a controlled environment
